frameworkVersion: '>=1.38.0 <2.0.0'

service: service_1

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-webpack
  # - serverless-plugin-aws-alerts

provider:
  name: aws
  runtime: nodejs10.x
  stage: api
  region: eu-west-1

  environment:
   
custom:
  # plugins
  # prune:
  #   automatic: true
  #   number: 1
  webpack:
    excludeFiles: '**/*.test.js'
    packager: 'yarn'
    includeModules: true

functions:
  list-stuff:
    handler: src/list.handler
    events:
      - http:
          path: list
          method: get
          cors: true